// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQeYOJvZ7V9bqL3IfJIECVAjbHxx0iUOQ',
    appId: '1:622485634549:web:337afa69347e06404cf4bc',
    messagingSenderId: '622485634549',
    projectId: 'ghazi-app-bcf25',
    authDomain: 'ghazi-app-bcf25.firebaseapp.com',
    storageBucket: 'ghazi-app-bcf25.firebasestorage.app',
    measurementId: 'G-DRZKWRW47W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhzPImtAwRd5fL9lzFuBlUCcHLuKMtco',
    appId: '1:622485634549:android:69a5aea442e1e7ac4cf4bc',
    messagingSenderId: '622485634549',
    projectId: 'ghazi-app-bcf25',
    storageBucket: 'ghazi-app-bcf25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9I_kC4RM4v1-ECxgNMtmfOt3EQDxWJC8',
    appId: '1:622485634549:ios:4e4e67181f8087d14cf4bc',
    messagingSenderId: '622485634549',
    projectId: 'ghazi-app-bcf25',
    storageBucket: 'ghazi-app-bcf25.firebasestorage.app',
    iosClientId:
        '622485634549-9d10tepc3ksu54fh5s5p32i3m34e55nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghaziMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9I_kC4RM4v1-ECxgNMtmfOt3EQDxWJC8',
    appId: '1:622485634549:ios:4e4e67181f8087d14cf4bc',
    messagingSenderId: '622485634549',
    projectId: 'ghazi-app-bcf25',
    storageBucket: 'ghazi-app-bcf25.firebasestorage.app',
    iosClientId:
        '622485634549-9d10tepc3ksu54fh5s5p32i3m34e55nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghaziMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQeYOJvZ7V9bqL3IfJIECVAjbHxx0iUOQ',
    appId: '1:622485634549:web:996309a8b66826a14cf4bc',
    messagingSenderId: '622485634549',
    projectId: 'ghazi-app-bcf25',
    authDomain: 'ghazi-app-bcf25.firebaseapp.com',
    storageBucket: 'ghazi-app-bcf25.firebasestorage.app',
    measurementId: 'G-MX65ECZE97',
  );
}
